# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=100)),
                ('dato_viejo', models.TextField()),
                ('dato_nuevo', models.TextField()),
                ('tabla', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuncionUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Funcion')),
            ],
        ),
        migrations.CreateModel(
            name='InterfazUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RolFuncion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Funcion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='funcionui',
            name='ui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.InterfazUsuario'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together=set([('usuario', 'rol')]),
        ),
        migrations.AlterUniqueTogether(
            name='rolfuncion',
            unique_together=set([('funcion', 'rol')]),
        ),
        migrations.AlterUniqueTogether(
            name='funcionui',
            unique_together=set([('funcion', 'ui')]),
        ),
    ]
