# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160314_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='ui',
            field=models.ManyToManyField(to='account.InterfazUsuario'),
        ),
        migrations.AddField(
            model_name='rol',
            name='funciones',
            field=models.ManyToManyField(to='account.Funcion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(to='account.Rol'),
        ),
    ]
