# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_cuenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Expone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Banda')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFiesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_manager.Persona')),
                ('nombre_artistico', models.CharField(max_length=255)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_manager.Persona')),
                ('nit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_manager.Evento')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_manager.Evento')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_exposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.TipoExposicion')),
            ],
        ),
        migrations.CreateModel(
            name='Fiesta',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_manager.Evento')),
                ('tipo_fiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.TipoFiesta')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Lugar'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.TipoEvento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Evento'),
        ),
        migrations.AddField(
            model_name='banda',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.EstiloMusical'),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='concierto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Concierto'),
        ),
        migrations.AddField(
            model_name='expone',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Artista'),
        ),
        migrations.AddField(
            model_name='expone',
            name='exposicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Exposicion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='presentacion',
            unique_together=set([('banda', 'concierto')]),
        ),
        migrations.AlterUniqueTogether(
            name='expone',
            unique_together=set([('exposicion', 'artista')]),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together=set([('evento', 'cliente')]),
        ),
    ]
