# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Evento', unique=True),
        ),
    ]
